import Qpf

/-- info: MvQPF.Arrow ?α : CurriedTypeFun 1 -/
#guard_msgs in
  #check MvQPF.Arrow ?α

data Arrow (α : Type _) β
  | mk : (α → β) → Arrow α β

/-- info: Arrow : Type → CurriedTypeFun 1 -/
#guard_msgs in
  #check (Arrow : Type → Type → Type)

-- Types generated by `data` are not as polymorphic as they could/should be,
--   so the following does not yet work:
-- `#check (Arrow : Type 1 → Type 1 → Type 1)`
