/-
Copyright (c) 2018 Jeremy Avigad. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jeremy Avigad, Simon Hudon
-/
module

public import QPFTypes.QPF.Basic
public import QPFTypes.PFunctor.Multivariate.M

/-!
# The final co-algebra of a multivariate qpf is again a qpf.

For a `(n+1)`-ary QPF `F (α₀,..,αₙ)`, we take the greatest fixed point of `F` with
regards to its last argument `αₙ`. The result is an `n`-ary functor: `Cofix F (α₀,..,αₙ₋₁)`.
Making `Cofix F` into a functor allows us to take the fixed point, compose with other functors
and take a fixed point again.

## Main definitions

* `Cofix.mk`     - constructor
* `Cofix.dest`   - destructor
* `Cofix.corec`  - corecursor: useful for formulating infinite, productive computations
* `Cofix.bisim`  - bisimulation: proof technique to show the equality of possibly infinite values
                    of `Cofix F α`

## Implementation notes

For `F` a QPF, we define `Cofix F α` in terms of the M-type of the polynomial functor `P` of `F`.
We define the relation `Mcongr` and take its quotient as the definition of `Cofix F α`.

`Mcongr` is taken as the weakest bisimulation on M-type. See
[avigad-carneiro-hudon2019] for more details.

## Reference

* Jeremy Avigad, Mario M. Carneiro and Simon Hudon.
  [*Data Types as Quotients of Polynomial Functors*][avigad-carneiro-hudon2019]
-/

@[expose] public section

namespace QPFTypes

universe u

/-! ### Quotient helper lemmas -/

/-- Factor a quotient map through another quotient with a weaker relation -/
private def Quot.factor {α : Type _} (r s : α → α → Prop) (h : ∀ x y, r x y → s x y) : Quot r → Quot s :=
  Quot.lift (Quot.mk s) fun x y rxy => Quot.sound (h x y rxy)

/-- The factoring composes correctly with Quot.mk -/
private theorem Quot.factor_mk_eq {α : Type _} (r s : α → α → Prop) (h : ∀ x y, r x y → s x y) :
    Quot.factor r s h ∘ Quot.mk _ = Quot.mk _ :=
  rfl

attribute [scoped grind .] Quot.sound
attribute [scoped grind =] Function.comp_def

open MvFunctor

namespace QPF

open TypeVec MvPFunctor

open MvFunctor (LiftP LiftR)

variable {n : Nat} {F : TypeVec.{u} (n + 1) → Type u} [q : QPF F]

/-- `corecF` is used as a basis for defining the corecursor of `Cofix F α`. `corecF`
uses corecursion to construct the M-type generated by `q.P` and uses function on `F`
as a corecursive step -/
def corecF {α : TypeVec n} {β : Type u} (g : β → F (α ::: β)) : β → q.P.M α :=
  M.corec q.P fun x => repr (g x)

theorem corecF_eq {α : TypeVec n} {β : Type u} (g : β → F (α ::: β)) (x : β) :
    (corecF g x).dest = (id ::: (corecF g)) <$$> (repr (g x)) := by
  rw [corecF, M.dest_corec]

/-- Characterization of desirable equivalence relations on M-types -/
def IsPrecongr {α : TypeVec n} (r : q.P.M α → q.P.M α → Prop) : Prop :=
  ∀ ⦃x y⦄, r x y →
    abs ((id ::: (Quot.mk r)) <$$> x.dest) =
      abs ((id ::: (Quot.mk r)) <$$> y.dest)

/-- Equivalence relation on M-types representing a value of type `Cofix F` -/
def Mcongr {α : TypeVec n} (x y : q.P.M α) : Prop :=
  ∃ r, IsPrecongr r ∧ r x y

/--
Greatest fixed point of functor F. The result is a functor with one fewer
parameters than the input. For `F a b c` a ternary functor, `Cofix F` is a
binary functor such that:

```lean
Cofix F a b = F a b (Cofix F a b)
```
-/
def Cofix (F : TypeVec (n + 1) → Type u) [q : QPF F] (α : TypeVec n) :=
  Quot (@Mcongr _ F q α)

instance {α : TypeVec n} [Inhabited q.P.A] [∀ i : Fin n, Inhabited (α i)] :
    Inhabited (Cofix F α) :=
  ⟨Quot.mk _ default⟩

/-- maps every element of the M type to a canonical representative -/
def mRepr {α : TypeVec n} : q.P.M α → q.P.M α :=
  corecF (abs ∘ M.dest q.P)

/-- the map function for the functor `Cofix F` -/
def Cofix.map {α β : TypeVec n} (g : α ⟹ β) : Cofix F α → Cofix F β :=
  Quot.lift (fun x => Quot.mk Mcongr (g <$$> x)) <| by
    rintro aa₁ aa₂ ⟨r, pr, ra₁a₂⟩; apply Quot.sound
    let r' b₁ b₂ := ∃ a₁ a₂ : q.P.M α, r a₁ a₂ ∧ b₁ = g <$$> a₁ ∧ b₂ = g <$$> a₂
    refine ⟨r', ?_, ⟨aa₁, aa₂, ra₁a₂, rfl, rfl⟩⟩
    rintro b₁ b₂ ⟨a₁, a₂, ra₁a₂, b₁eq, b₂eq⟩
    let u : Quot r → Quot r' :=
      Quot.lift (fun x => Quot.mk r' (g <$$> x))
        (fun a₁ a₂ rab => Quot.sound ⟨a₁, a₂, rab, rfl, rfl⟩)
    have hu : (Quot.mk r' ∘ fun x => g <$$> x) = u ∘ Quot.mk r := rfl
    rw [b₁eq, b₂eq, M.dest_map, M.dest_map]
    rw [MvFunctor.map_map, MvFunctor.map_map]
    rw [← appendFun_comp, id_comp, hu, ← comp_id g, appendFun_comp]
    rw [← MvFunctor.map_map, ← MvFunctor.map_map, abs_map, pr ra₁a₂, ← abs_map]

instance Cofix.mvfunctor : MvFunctor (Cofix F) where map := @Cofix.map _ _ _

/-- Corecursor for `Cofix F` -/
def Cofix.corec {α : TypeVec n} {β : Type u} (g : β → F (α ::: β)) : β → Cofix F α := fun x =>
  Quot.mk _ (corecF g x)

set_option backward.isDefEq.respectTransparency false in
/-- Destructor for `Cofix F α` -/
def Cofix.dest {α : TypeVec n} : Cofix F α → F (α ::: (Cofix F α)) :=
  Quot.lift ((id ::: (Quot.mk Mcongr)) <$$> abs ·.dest) <| by
    rintro x y ⟨r, pr, rxy⟩
    have : ∀ x y, r x y → Mcongr x y := by
      intro x y h
      exact ⟨r, pr, h⟩
    dsimp only [← Quot.factor_mk_eq _ _ this]
    rw [appendFun_comp_id, comp_map, ← abs_map, pr rxy, abs_map, ← comp_map,
      ← appendFun_comp_id]

/-- Constructor for `Cofix F` -/
def Cofix.mk {α : TypeVec n} : F (α ::: Cofix F α) → Cofix F α :=
  Cofix.corec fun x => (appendFun id fun i : Cofix F α => Cofix.dest.{u} i) <$$> x

/-- Abstraction function for `Cofix F α` -/
def Cofix.abs {α} : q.P.M α → Cofix F α :=
  Quot.mk _

/-- Representation function for `Cofix F α` -/
def Cofix.repr {α} : Cofix F α → q.P.M α :=
  M.corec q.P <| q.repr ∘ Cofix.dest

/-!
## Bisimulation principles for `Cofix F`
-/

private theorem Cofix.bisim_aux {α : TypeVec n} (r : Cofix F α → Cofix F α → Prop) (h' : ∀ x, r x x)
    (h : ∀ x y, r x y →
      appendFun id (Quot.mk r) <$$> Cofix.dest x = appendFun id (Quot.mk r) <$$> Cofix.dest y) :
    ∀ x y, r x y → x = y := by
  intro x
  rcases x with ⟨x⟩
  intro y
  rcases y with ⟨y⟩
  intro rxy
  let r' := fun x y => r (Quot.mk _ x) (Quot.mk _ y)
  refine Quot.sound ⟨r', ?_, rxy⟩
  show IsPrecongr r'
  intro a b r'ab
  have h₀ : (TypeVec.id ::: Quot.mk r ∘ Quot.mk Mcongr) <$$> QPF.abs a.dest =
            (TypeVec.id ::: Quot.mk r ∘ Quot.mk Mcongr) <$$> QPF.abs b.dest := by
    have h := h (Quot.mk Mcongr a) (Quot.mk Mcongr b) r'ab
    simpa [Cofix.dest, ← comp_map, ← appendFun_comp] using h
  have h₁ : ∀ u v, Mcongr u v → Quot.mk r' u = Quot.mk r' v := by grind
  let f : Quot r → Quot r' := Quot.lift (Quot.lift (Quot.mk r') h₁) <| by
    intro c d
    cases c using Quot.inductionOn
    cases d using Quot.inductionOn
    grind
  have hf : f ∘ Quot.mk r ∘ Quot.mk Mcongr = Quot.mk r' := rfl
  grind

/-- Bisimulation principle using `map` and `Quot.mk` to match and relate children of two trees. -/
theorem Cofix.bisim_rel {α : TypeVec n} (r : Cofix F α → Cofix F α → Prop)
    (h : ∀ x y, r x y →
      (id ::: Quot.mk r) <$$> Cofix.dest x = (id ::: Quot.mk r) <$$> Cofix.dest y) :
    ∀ x y, r x y → x = y := by
  let r' (x y) := x = y ∨ r x y
  intro x y rxy
  apply Cofix.bisim_aux r'
  · intro x; left; rfl
  · intro x y r'xy
    cases r'xy with
    | inl h' => rw [h']
    | inr r'xy =>
      have hf : ∀ x y, r x y → r' x y := by grind
      grind [Quot.factor_mk_eq _ _ hf]
  · right; exact rxy

/-- Bisimulation principle using `LiftR` to match and relate children of two trees. -/
theorem Cofix.bisim {α : TypeVec n} (r : Cofix F α → Cofix F α → Prop)
    (h : ∀ x y, r x y → LiftR (RelLast α r) (Cofix.dest x) (Cofix.dest y)) :
    ∀ x y, r x y → x = y := by
  apply Cofix.bisim_rel
  intro x y rxy
  rcases (liftR_iff (fun a b => RelLast α r b) (Cofix.dest x) (Cofix.dest y)).mp (h x y rxy)
    with ⟨a, f₀, f₁, dxeq, dyeq, h'⟩
  rw [dxeq, dyeq, ← abs_map, ← abs_map, MvPFunctor.map_eq, MvPFunctor.map_eq]
  rw [← split_dropFun_lastFun f₀, ← split_dropFun_lastFun f₁]
  rw [appendFun_comp_splitFun, appendFun_comp_splitFun]
  erw [id_comp, id_comp]
  congr 2
  funext i j
  rcases i with _ | i
  · apply Quot.sound;
    apply h' _ j
  · show f₀ _ j = f₁ _ j
    apply h' _ j

/-!
## Cofix Lemmas
-/

@[grind =]
theorem Cofix.dest_corec {α : TypeVec n} {β : Type u} (g : β → F (α ::: β)) (x : β) :
    Cofix.dest (Cofix.corec g x) = (id ::: Cofix.corec g) <$$> g x := by
  unfold Cofix.dest Cofix.corec
  dsimp
  rw [corecF_eq, abs_map, abs_repr, ← QPF.comp_map, ← appendFun_comp, id_comp]
  rfl

@[simp, grind =]
theorem Cofix.mk_dest {α : TypeVec n} (x : Cofix F α) : Cofix.mk (Cofix.dest x) = x := by
  apply Cofix.bisim_rel (fun x y : Cofix F α => x = Cofix.mk (Cofix.dest y)) _ _ _ rfl
  dsimp
  intro x y heq
  rw [heq, Cofix.mk, Cofix.dest_corec]
  rw [← QPF.comp_map, ← appendFun_comp, id_comp]
  rw [← QPF.comp_map, ← appendFun_comp, id_comp, ← Cofix.mk]
  congr 2
  grind

@[simp, grind =]
theorem Cofix.dest_mk {α : TypeVec n} (x : F (α ::: Cofix F α)) :
    Cofix.dest (Cofix.mk x) = x := by
  rw [Cofix.mk, Cofix.dest_corec, ← Cofix.mk]
  have : Cofix.mk ∘ Cofix.dest = @_root_.id (Cofix F α) := funext Cofix.mk_dest
  grind

@[ext, grind .]
theorem Cofix.ext {α : TypeVec n} (x y : Cofix F α) (h : x.dest = y.dest) : x = y := by
  rw [← Cofix.mk_dest x, h, Cofix.mk_dest]

theorem Cofix.ext_mk {α : TypeVec n} (x y : F (α ::: Cofix F α)) (h : Cofix.mk x = Cofix.mk y) :
    x = y := by
  rw [← Cofix.dest_mk x, h, Cofix.dest_mk]

/-!
### QPF instance for Cofix
-/

theorem Cofix.abs_repr {α} (x : Cofix F α) : Quot.mk Mcongr (Cofix.repr x) = x := by
  let R := fun a b : Cofix F α => Quot.mk Mcongr (Cofix.repr b) = a
  apply Cofix.bisim_rel R
  · rintro a b rfl
    cases b using Quot.ind with | mk b =>
    simp only [Cofix.dest, Cofix.repr, M.dest_corec, abs_map, Function.comp_def]
    rw [← QPF.comp_map, ← QPF.comp_map, QPF.abs_repr]
    congr 1
    apply eq_of_drop_last_eq
    · grind
    · simp only [lastFun_comp, lastFun_appendFun]
      funext z
      exact Quot.sound rfl
  · rfl

/-- `Cofix F` is a QPF -/
instance qpfCofix : QPF (Cofix F) where
  P        := q.P.mp
  abs      := Quot.mk Mcongr
  repr     := Cofix.repr
  abs_repr := Cofix.abs_repr
  abs_map  := by intros; rfl

end QPF

end QPFTypes
